### ISSUE TITLE
404 when going to https://pineapple-proxy-dao.github.io

### ISSUE THREAD

**Issue by gyrusdentatus** [Pineapple-Proxy-DAO/web#9]
https://pineapple-proxy-dao.github.io/web should be the root dir. Easy to fix in settings, I know how to do it in nginx, apache or whatever but not sure how it works with github pages.

**Comment by sven-hash** [comment]
It will be solved when a domain name will be set

**Comment by gyrusdentatus** [comment]
makes sense, yeah.
